FROM denoland/deno:alpine-1.16.4
# FROM denoland/deno:debian-1.16.4
# FROM denoland/deno:ubuntu-1.16.4
# FROM denoland/deno:alpine-1.14.3
# FROM denoland/deno:alpine-1.13.2

# RUN apk update && \
#     apk add \
#         git \
#         inotify-tools

# RUN deno run -A https://deno.land/x/aleph/install.ts "0.2.28"
# RUN deno run -A https://deno.land/x/aleph/install.ts "0.3.0-beta.1"
RUN deno run -A https://deno.land/x/aleph/install.ts "0.3.0-beta.19"

RUN adduser -D deno-user
# USER deno-user
